version: "3.9"

services:
  archivist:
    image: archivist:dev
    build:
      context: .
      target: dev
      args:
        APP_UID: ${ARCHIVIST_UID:-1000}
        APP_GID: ${ARCHIVIST_GID:-1000}
    # run infinitely
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/archivist
