[tool.poetry]
name = "salesforce-archivist"
version = "0.1.0"
description = "Salesforce files archiving tool"
authors = ["piotrekkr <piotrekkr@users.noreply.github.com>"]
readme = "README.md"
packages = [
  { include = "salesforce_archivist", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"
simple-salesforce = "^1.12.5"
python-dotenv = "^1.0.0"
PyYAML = "^6.0.1"
click = "^8.1.7"
schema = "^0.7.5"
python-dateutil = "^2.8.2"
types-PyYAML = "^6.0.12.12"
pytest = "^7.4.3"
pytest-mock = "^3.12.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
flake8 = "^6.1.0"
mypy = "^1.7.1"
tomli = "^2.0.1"
black = "^23.12.0"
types-requests = "^2.31.0.20240106"
poethepoet = "^0.24.4"

[tool.poetry.scripts]
archivist = 'salesforce_archivist.cli:cli'

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "test",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
files = "src"
disallow_untyped_defs = true
ignore_missing_imports = true
show_error_codes = true
no_implicit_optional = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
warn_return_any = true
warn_unused_ignores = true

[tool.isort]
profile = "black"
src_paths = ["src/salesforce_archivist", "test"]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.black]
preview = true
line-length = 120
target-version = ['py310']
include = '\.pyi?$'


[tool.poe.tasks.test]
help = "Run tests"
cmd  = "pytest ."

[tool.poe.tasks.isort]
help = "Run import sorting"
cmd  = "isort ."

[tool.poe.tasks.black]
help = "Run code formatting"
cmd  = "black ."

[tool.poe.tasks.flake8]
help = "Run code linting"
cmd  = "flake8"

[tool.poe.tasks.mypy]
help = "Run mypy"
cmd = "mypy"

[tool.poe.tasks.cs]
help = "Run code style tools"
sequence  = ["isort", "black", "flake8", "mypy"]
