[tool.poetry]
name = "salesforce-archivist"
version = "0.1.0"
description = "Salesforce files archiving tool"
authors = ["piotrekkr <piotrekkr@users.noreply.github.com>"]
readme = "README.md"
packages = [
  { include = "salesforce_archivist", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.10"
simple-salesforce = "^1.12.5"
python-dotenv = "^1.0.0"
PyYAML = "^6.0.1"
click = "^8.1.7"
schema = "^0.7.5"
python-dateutil = "^2.8.2"
types-PyYAML = "^6.0.12.12"
pytest = "^7.4.3"
pytest-mock = "^3.12.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
flake8 = "^6.1.0"
mypy = "^1.7.1"
tomli = "^2.0.1"
black = "^23.12.0"
types-requests = "^2.31.0.20240106"

[tool.poetry.scripts]
archivist = 'salesforce_archivist.cli:cli'

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
